### ISSUE TITLE
数组溢出

### ISSUE THREAD

**Issue by cehnsi1122** [huashishaojie/IDS-CNN#1]
我运行代码的时候，出现数组溢出的现象，不知是环境的问题还是版本的问题，我用3.7的版本运行的，其中还有一处的label_train参数不识别
![QQ图片20190701165126](https://user-images.githubusercontent.com/52162671/60423314-8376d380-9c20-11e9-9cb9-11ba0c1f286d.jpg)

**Comment by liaoxun** [comment]
我也遇到了这个情况，请问解决了吗

**Comment by liaoxun** [comment]
Traceback (most recent call last):
  File "D:/pyCharm/IDS_CNN/cnn_main.py", line 84, in <module>
    load_data()
  File "D:/pyCharm/IDS_CNN/cnn_main.py", line 65, in load_data
    label_list[int(i[41])] = 1
IndexError: list index out of range

**Comment by cehnsi1122** [comment]
解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liaoxun"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月19日(星期四) 下午2:18
收件人:&nbsp;"huashishaojie/IDS-CNN"<IDS-CNN@noreply.github.com&gt;;
抄送:&nbsp;"一路向北"<935506920@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1)




我也遇到了这个情况，请问解决了吗

**Comment by liaoxun** [comment]
您好，请问可以详细说一下吗，我是新人网上看到这个代码，想拿来跑一跑，万分感谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "cehnsi1122"<notifications@github.com&gt;; 
发送时间: 2019年12月19日(星期四) 下午2:29
收件人: "huashishaojie/IDS-CNN"<IDS-CNN@noreply.github.com&gt;; 
抄送: "759897779"<759897779@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [huashishaojie/IDS-CNN] 数组溢出 (#1)



解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"liaoxun"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2019年12月19日(星期四) 下午2:18 
 收件人:&amp;nbsp;"huashishaojie/IDS-CNN"<IDS-CNN@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"一路向北"<935506920@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1) 
 
 
 
 
 我也遇到了这个情况，请问解决了吗

**Comment by ashin1256** [comment]
> 您好，请问可以详细说一下吗，我是新人网上看到这个代码，想拿来跑一跑，万分感谢
> […](#)
> ------------------＆nbsp;原始邮件＆nbsp; ------------------发件人：“ cehnsi1122” < notifications@github.com> ;; 发送时间：2019年12月19日（星期四）下午2:29收件人：“ huashishaojie / IDS-CNN” <IDS-CNN@noreply.github.com> ;；抄送：“ 759897779” <759897779@qq.com> ;; “评论” <comment@noreply.github.com> ;; 主题：Re：[huashishaojie / IDS-CNN]分散重叠（[＃1](https://github.com/huashishaojie/IDS-CNN/issues/1)）解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后都有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了
> ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 发件人:&amp;nbsp;"liaoxun"<notifications@github.com&amp;gt;; 发送时间:&amp;nbsp;2019年12月19日(星期四) 下午2:18 收件人:&amp;nbsp;"huashishaojie/IDS-CNN"<IDS-CNN@noreply.github.com&amp;gt;; 抄送:&amp;nbsp;"一路向北"<935506920@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 主题:&amp;nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1) 我也遇到了这个情况，请问解决了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

你跑成功了嘛

**Comment by MarioKKW** [comment]
写csv文件的时候 加上 newline=' '   就不会有空行了

**Comment by wxhn1225** [comment]
> 

能具体说说是在哪行代码加吗

**Comment by HFNUWG** [comment]
这个具体在哪个地方里加代码

**Comment by NaturalShower** [comment]
> > 
> 
> 能具体说说是在哪行代码加吗

【handle2.py    line9】     data_to_flie=open(handled_file, 'w')   改为  data_to_flie=open(handled_file, 'w',newline=' ')

**Comment by wxhn1225** [comment]
> 

好的，谢谢，之前让朋友看，也是在这里加

**Comment by wxhn1225** [comment]
> > > 
> > 
> > 
> > 能具体说说是在哪行代码加吗
> 
> 【handle2.py line9】 data_to_flie=open(handled_file, 'w') 改为 data_to_flie=open(handled_file, 'w',newline=' ')

想问下你这个代码完整运行出来了吗

**Comment by HFNUWG** [comment]
> > > > 
> > > 
> > > 
> > > 能具体说说是在哪行代码加吗
> > 
> > 
> > 【handle2.py line9】 data_to_flie=open(handled_file, 'w') 改为 data_to_flie=open(handled_file, 'w',newline=' ')
> 
> 想问下你这个代码完整运行出来了吗
这个我加了之后为啥还是不可以呀

**Comment by HFNUWG** [comment]
Traceback (most recent call last):
  File "C:\Users\HUAWEI\Desktop\IDS-CNN-master (1)\IDS-CNN-master\handle2.py", line 72, in <module>
    preHandle()
  File "C:\Users\HUAWEI\Desktop\IDS-CNN-master (1)\IDS-CNN-master\handle2.py", line 19, in preHandle
    temp_line[1] = handleProtocol(i)  # 将源文件行中3种协议类型转换成数字标识
  File "C:\Users\HUAWEI\Desktop\IDS-CNN-master (1)\IDS-CNN-master\handle2.py", line 36, in handleProtocol
    if input[1] in protoclo_list:
IndexError: list index out of range
代码如下
def preHandle():
    source_file = '/Users/HUAWEI/Desktop/IDS-CNN-master (1)/IDS-CNN-master/kddcup.data_10_percent_corrected'
    handled_file = '/Users/HUAWEI/Desktop/IDS-CNN-master (1)/IDS-CNN-master/kddcup.data_10_percent_corrected.csv'
    data_to_flie = open(handled_file, 'w', newline='')
    with (open(source_file, 'r')) as data_from:
这是啥原因呢

**Comment by HFNUWG** [comment]
> 解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"liaoxun"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月19日(星期四) 下午2:18 收件人:&nbsp;"huashishaojie/IDS-CNN"<IDS-CNN@noreply.github.com&gt;; 抄送:&nbsp;"一路向北"<935506920@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1) 我也遇到了这个情况，请问解决了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我想问一下，这个项目是需要准备那些工具，我现在用编译器pycharm，还有anaconda，但是在运行代码的时候在读取文件处加了newline=''，还是一直显示 list index out of range.目前陷入了死胡同。所以想请问一下大佬。

**Comment by HFNUWG** [comment]
> 解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了
> [...](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"liaoxun"<notifications@github.com&gt;; 发送时间:&nbsp;2019年12月19日(星期四) 下午2:18 收件人:&nbsp;"huashishaojie/IDS-CNN"<IDS-CNN@noreply.github.com&gt;; 抄送:&nbsp;"一路向北"<935506920@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1) 我也遇到了这个情况，请问解决了吗 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

你好，我想问一下，这个项目是需要准备那些工具，我现在用编译器pycharm，还有anaconda，但是在运行代码的时候在读取文件处加了newline=''，还是一直显示 list index out of range.目前陷入了死胡同。所以想请问一下大佬。

**Comment by huahuayahei** [comment]
> > 解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了 [...](#) ------------------ 原始邮件 ------------------ 发件人： “辽讯”<[notifications@github.com](mailto:notifications@github.com)>;发送时间： 2019年12月19日（星期四） 下午2：18 收件人： “huashishaojie/IDS-CNN”<[IDS-CNN@noreply.github.com](mailto:IDS-CNN@noreply.github.com)>;抄送： “一路向北”<[935506920@qq.com](mailto:935506920@qq.com)>;”作者“<[author@noreply.github.com](mailto:author@noreply.github.com)>;主题： Re： [huashishaojie/IDS-CNN] 数组溢出 （#1） 我也遇到了这个情况，请问解决了吗 — 你收到这个是因为你写了这个线程。直接回复此电子邮件，在 GitHub 上查看或取消订阅。
> 
> 你好，我想问一下，这个项目是需要准备那些工具，我现在用编译器pycharm，还有anaconda，但是在运行代码的时候在读取文件处加了newline=''，还是一直显示列表索引 out of range.目前陷入了死胡同。所以想请问一下大佬。

请问一下，您这个问题解决了吗

**Comment by HFNUWG** [comment]
> > > 解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了 [...](#) ------------------ 原始邮件 ------------------ 发件人： “辽讯”<[notifications@github.com](mailto:notifications@github.com)>;发送时间： 2019年12月19日（星期四） 下午2：18 收件人： “huashishaojie/IDS-CNN”<[IDS-CNN@noreply.github.com](mailto:IDS-CNN@noreply.github.com)>;抄送： “一路向北”<[935506920@qq.com](mailto:935506920@qq.com)>;”作者“<[author@noreply.github.com](mailto:author@noreply.github.com)>;主题： Re： [huashishaojie/IDS-CNN] 数组溢出 （#1） 我也遇到了这个情况，请问解决了吗 — 你收到这个是因为你写了这个线程。直接回复此电子邮件，在 GitHub 上查看或取消订阅。
> > 
> > 
> > 你好，我想问一下，这个项目是需要准备那些工具，我现在用编译器pycharm，还有anaconda，但是在运行代码的时候在读取文件处加了newline=''，还是一直显示列表索引 out of range.目前陷入了死胡同。所以想请问一下大佬。
> 
> 请问一下，您这个问题解决了吗

还没有呢，现在陷入死胡同了，你解决了吗？

**Comment by NaturalShower** [comment]
tensorboard可以显示模型架构，但不能显示准确率等数据分析。我还没搞懂具体代码逻辑。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huashishaojie/IDS-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月5日(星期二) 上午9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1)





     
能具体说说是在哪行代码加吗
  
【handle2.py line9】 data_to_flie=open(handled_file, 'w') 改为 data_to_flie=open(handled_file, 'w',newline=' ')
  
想问下你这个代码完整运行出来了吗

**Comment by huahuayahei** [comment]
我在main.py这个文件的109行加了一个int，改成了这样label_list[int(i[41])] = 1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "huashishaojie/IDS-CNN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月24日(星期天) 中午12:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1)





    
解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了 ... ------------------ 原始邮件 ------------------ 发件人： ***@***.***&gt;;发送时间： 2019年12月19日（星期四） 下午2：18 收件人： ***@***.***&gt;;抄送： ***@***.******@***.***&gt;;主题： Re： [huashishaojie/IDS-CNN] 数组溢出 （#1） 我也遇到了这个情况，请问解决了吗 — 你收到这个是因为你写了这个线程。直接回复此电子邮件，在 GitHub 上查看或取消订阅。
  
你好，我想问一下，这个项目是需要准备那些工具，我现在用编译器pycharm，还有anaconda，但是在运行代码的时候在读取文件处加了newline=''，还是一直显示列表索引 out of range.目前陷入了死胡同。所以想请问一下大佬。
  
请问一下，您这个问题解决了吗
  
还没有呢，现在陷入死胡同了，你解决了吗？

**Comment by wanzi-gif** [comment]
> 我在main.py这个文件的109行加了一个int，改成了这样label_list[int(i[41])] = 1
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "huashishaojie/IDS-CNN" ***@***.***&gt;; 发送时间:&nbsp;2022年4月24日(星期天) 中午12:03 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [huashishaojie/IDS-CNN] 数组溢出 (#1) 解决了，出现这种原因是因为源代码中处理数据之后，每一行数据之后会有一行空行，在取数据时，加上一个判断语句如果是空行pass就行了 ... ------------------ 原始邮件 ------------------ 发件人： ***@***.***&gt;;发送时间： 2019年12月19日（星期四） 下午2：18 收件人： ***@***.***&gt;;抄送： ***@***.******@***.***&gt;;主题： Re： [huashishaojie/IDS-CNN] 数组溢出 （#1） 我也遇到了这个情况，请问解决了吗 — 你收到这个是因为你写了这个线程。直接回复此电子邮件，在 GitHub 上查看或取消订阅。 你好，我想问一下，这个项目是需要准备那些工具，我现在用编译器pycharm，还有anaconda，但是在运行代码的时候在读取文件处加了newline=''，还是一直显示列表索引 out of range.目前陷入了死胡同。所以想请问一下大佬。 请问一下，您这个问题解决了吗 还没有呢，现在陷入死胡同了，你解决了吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

加完以后还是报错ValueError: Cannot feed value of shape (1000, 23) for Tensor 'inputs/picLabel:0', which has shape '(?, 2)'  该怎么解决呀

**Comment by zzfhadr** [comment]
换行符的问题：如果在打开文件时没有使用 newline=''，有时 Python 可能会错误地处理换行符，导致空行。把handle.py里面的改改，这样生成的CSV就不会有空行了
